INSERT INTO fonte (nome) VALUES ('BB - Coutinho');
INSERT INTO fonte (nome) VALUES ('BB - Ingrid');
INSERT INTO fonte (nome) VALUES ('BB - poupança 51 - Coutinho');
INSERT INTO fonte (nome) VALUES ('BB - poupança 96 - Coutinho');
INSERT INTO fonte (nome) VALUES ('BB - poupança 51 - Ingrid');
INSERT INTO fonte (nome) VALUES ('BB - poupança 96 - Ingrid');
INSERT INTO fonte (nome) VALUES ('BB - Cartão visa - Coutinho');
INSERT INTO fonte (nome) VALUES ('BB - Cartão master - Coutinho');
INSERT INTO fonte (nome) VALUES ('BB - Cartão visa - Ingrid');
INSERT INTO categoria (nome) VALUES ('Combustível');
INSERT INTO categoria (nome) VALUES ('Alimentação');
INSERT INTO categoria (nome) VALUES ('Energia');
INSERT INTO categoria (nome) VALUES ('Água');
INSERT INTO categoria (nome) VALUES ('Educação');
INSERT INTO categoria (nome) VALUES ('Condomínio');
INSERT INTO categoria (nome) VALUES ('Cultura');
INSERT INTO categoria (nome) VALUES ('Lazer');
INSERT INTO categoria (nome) VALUES ('Medicamentos');
INSERT INTO categoria (nome) VALUES ('Supermercados');
INSERT INTO categoria (nome) VALUES ('Telefone');
INSERT INTO credor (nome) VALUES ('Picanha do Jonas');
INSERT INTO credor (nome) VALUES ('Tropeiro');
INSERT INTO credor (nome) VALUES ('Art Pão');
INSERT INTO favorecido (nome) VALUES ('Coutinho');
INSERT INTO favorecido (nome) VALUES ('Ingrid');
INSERT INTO favorecido (nome) VALUES ('Gabriel');